## Følgende variabler må eksistere for å bruke denne propertyfilen:
## - SRVPENSJON_USERNAME
## - SRVPENSJON_PASSWORD
## - OPENAM_SECRET

euxbasis.v1:
  #  url: 'http://10.33.44.43:9090/cpi'
  url: 'https://eux-app.nais.preprod.local/cpi'
#  url: 'https://eux-app-t8.nais.preprod.local/cpi'
#  url: 'http://localhost:9090/cpi'

virksomhet.person.v3:
  #  endpointurl: 'https://wasapp-t7.adeo.no/tpsws/ws/Person/v3'  # maskert-data
  endpointurl: 'https://wasapp-t8.adeo.no/tpsws/ws/Person/v3' # prod-data

aktoerregister.api.v1:
  url: 'https://app-t8.adeo.no/aktoerregister/api/v1'

pensjonsinformasjon:
  api:
    v1:
      url: 'https://wasapp-t5.adeo.no/pensjon-ws/api/pensjonsinformasjon/v1'

eessi-security-token-service:
  url: 'https://security-token-service-t10.nais.preprod.local/rest/v1/sts/token'

srveessipensjon:
  username: '${SRVEESSIPENSJON_USERNAME}'
  password: '${SRVEESSIPENSJON_PASSWORD}'

app:
  name: 'DEVELOP'
  version: '0.1'

securitytokenservice:
  url: 'https://sts-t8.test.local/SecurityTokenServiceProvider/'

server:
  port: '8081'

no.nav.security.oidc:
  issuer.oidc:
    discoveryurl: 'https://isso-t.adeo.no:443/isso/oauth2/.well-known/openid-configuration'
    accepted_audience: 'eessi-fagmodul-localhost,eessi-fagmodul-t8,freg-token-provider-t0,eessi-pensjon-frontend-api-t8,eessi-pensjon-frontend-api-fss-t8,eux-app-t8,ida-t'

http.proxy.parametername:

management:
  endpoints:
    enabled-by-default: 'true'
    jmx:
      exposure.include: '*'
    web:
      exposure.include: '*'

rinaaction:
    waittime: '5000'

