freg:
  security:
    oidc:
#      ignored-paths: '/internal/**,/actuator/**,/error**,/login**'
      refresh:
        enabled: 'false'
      auth:
#        enabled: 'true'
        header-filter-enabled: 'true'
        cookie-filter-enabled: 'false'
      login:
        enabled: 'false'
      openam:
        url: 'https://isso-t.adeo.no:443/isso'
      client-id: 'eessi-fagmodul-localhost'
      client-secret: 'Test1234'

security:
  oidc:
    host: '${freg.security.oidc.openam.url}'
  openam:
    username: 'eessi-fagmodul-localhost'
    password: 'Test1234'
    redirectUri: 'http://localhost:8080/login/oauth2/code/openam'

eessibasis:
#  url: 'https://eux-app.nais.preprod.local'
  url: 'http://localhost:9090'

aktoer.v2:
  endpointurl: 'https://app-t8.adeo.no/aktoerid/AktoerService/v2'

virksomhet.person.v3:
  endpointurl: 'https://wasapp-t7.adeo.no/tpsws/ws/Person/v3' # med rett mask i navn og person
#  endpointurl: 'https://wasapp-t8.adeo.no/tpsws/ws/Person/v3' # relle data ekte person

credentials:
  srvpensjon:
    username: 'srvPensjon'
    password: 'Ash5SoxP'

app:
  name: 'DEVELOP'
  version: '0.1'

securitytokenservice:
  url: 'https://sts-t8.test.local/SecurityTokenServiceProvider/'

server:
  port: '8081'
