freg:
  security:
    oidc:
      auth:
        header-filter-enabled: 'false'
        cookie-filter-enabled: 'true'
      login:
        enabled: 'true'
        path: '/login/oauth2/code/openam'
      openam:
        url: 'https://isso-t.adeo.no:443/isso'
      client-id: 'eessi-fagmodul-localhost'
      client-secret: 'Test1234'

eessibasis:
  url: https://eux-app.nais.preprod.local
  username: srvPensjon
  password: Ash5SoxP

aktoer.v2:
  endpointurl: https://app-t8.adeo.no/aktoerid/AktoerService/v2

credentials:
  srvpensjon:
    username: srvPensjon
    password: Ash5SoxP

app:
  name: DEVELOP
  version: 0.1

securitytokenservice:
  url: https://sts-t8.test.local/SecurityTokenServiceProvider/
