## Følgende variabler må eksistere for å bruke denne propertyfilen:
## - SRVPENSJON_USERNAME
## - SRVPENSJON_PASSWORD
## - OPENAM_SECRET

eessibasis:
#  url: 'https://eux-app.nais.preprod.local'
  url: 'http://localhost:9090'

aktoer.v2:
  endpointurl: 'https://app-t8.adeo.no/aktoerid/AktoerService/v2'

virksomhet.person.v3:
  endpointurl: 'https://wasapp-t7.adeo.no/tpsws/ws/Person/v3'  # maskert-data
#  endpointurl: 'https://wasapp-t8.adeo.no/tpsws/ws/Person/v3' # prod-data

credentials:
  srvpensjon:
    username: '${SRVPENSJON_USERNAME}'
    password: '${SRVPENSJON_PASSWORD}'

app:
  name: 'DEVELOP'
  version: '0.1'

securitytokenservice:
  url: 'https://sts-t8.test.local/SecurityTokenServiceProvider/'

server:
  port: '8081'

no.nav.security.oidc:
  issuer.oidc:
    discoveryurl: 'https://isso-t.adeo.no:443/isso/oauth2/.well-known/openid-configuration'
    accepted_audience: 'eessi-fagmodul-frontend-t8,eessi-fagmodul-localhost,eessi-fagmodul-t8,freg-token-provider-t0'

http.proxy.parametername:

management:
  endpoints:
    enabled-by-default: 'true'
    jmx:
      exposure.include: '*'
    web:
      exposure.include: '*'
