kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-fagmodul-q2
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  kafka:
    pool: nav-dev
  envFrom:
    - secret: fagmodul-dev #secret name in Google Secret Manager
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: 6e921c7e-7b22-4c9a-9ff6-ee3719e3c4ba #Tilgang til 0000-ga-eessi-clerk-pensjon
          - id: 79c6b5b5-1144-495c-a2c9-78aebfb5faf4 #Tilgang til 0000-ga-eessi-clerk-ufore
        extra:
          - NAVident
  gcp:
    buckets:
      - name: eessi-pensjon-gjenny-dev
        lifecycleCondition:
          age: 365
          createdBefore: 2020-01-01
          numNewerVersions: 2
          withState: ANY
        uniformBucketLevelAccess: true
      - name: eessi-pensjon-p8000-dev
        retentionPeriodDays: 40
        lifecycleCondition:
          age: 365
          createdBefore: 2020-01-01
          numNewerVersions: 2
          withState: ANY
        uniformBucketLevelAccess: true
  accessPolicy:
    outbound:
      rules:
        - application: eessi-pensjon-prefill-q2
          namespace: eessipensjon
          cluster: dev-gcp
      external:
        - host: rina-ss1-q.adeo.no
        - host: kodeverk-api.nav.no
        - host: pensjon-q2.pensjon-pen-q2
        - host: saf-q2.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
        - host: pensjon-pen-q2.dev-fss-pub.nais.io
        - host: eux-rina-api-gcp-q2.intern.dev.nav.no
        - host: eessi-pensjon-prefill-q2.intern.dev.nav.no
        - host: eessi-pensjon-journalforing-q2.intern.dev.nav.no
    inbound:
      rules:
        - application: eessi-pensjon-frontend-ui-q2
          namespace: eessipensjon
          cluster: dev-gcp
        - application: eessi-pensjon-saksbehandling-api-q2
          namespace: eessipensjon
          cluster: dev-gcp
        - application: eessi-pensjon-journalforing-q2
          namespace: eessipensjon
          cluster: dev-gcp

        - application: pensjon-pen-q2
          namespace: pensjon-q2
          cluster: dev-fss

  webproxy: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: GCP_BUCKET_GJENNY
      value: eessi-pensjon-gjenny-dev
    - name: GCP_BUCKET_P8000
      value: eessi-pensjon-p8000-dev

    - name: PENSJONSINFORMASJON_URL
      value: https://pensjon-pen-q2.dev-fss-pub.nais.io/pen/api/pensjonsinformasjon/v1
    - name: EESSIPEN_EUX_RINA_URL
      value: https://eux-rina-api-gcp-q2.intern.dev.nav.no/cpi
    - name: EESSIPENSJON_PREFILL_GCP_URL
      value: https://eessi-pensjon-prefill-q2.intern.dev.nav.no
    - name: RINA_HOST_URL
      value: rina-ss1-q.adeo.no
    - name: SAF_GRAPHQL_URL
      value: https://saf-q2.dev-fss-pub.nais.io/graphql
    - name: SAF_HENTDOKUMENT_URL
      value: https://saf-q2.dev-fss-pub.nais.io/rest/hentdokument
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: KAFKA_STATISTIKK_TOPICNAME
      value: eessipensjon.privat-statistikk-q2
    - name: KAFKA_AUTOMATISERING_TOPIC
      value: eessipensjon.public-automatisering-q2
    - name: KODEVERK_URL
      value: https://kodeverk-api.nav.no
    - name: AZURE_APP_PDL_CLIENT_ID
      value: dev-fss.pdl.pdl-api
    - name: AZURE_APP_PREFILL_CLIENT_ID
      value: dev-gcp.eessipensjon.eessi-pensjon-prefill-q2
    - name: AZURE_APP_EUX_CLIENT_ID
      value: dev-gcp.eessibasis.eux-rina-api-q2
    - name: AZURE_APP_KODEVERK_CLIENT_ID
      value: dev-gcp.team-rocket.kodeverk-api
    - name: AZURE_APP_SAF_CLIENT_ID
      value: dev-fss.teamdokumenthandtering.saf
    - name: AZURE_APP_PEN_CLIENT_ID
      value: dev-fss.pensjon-q2.pensjon-pen-q2

    - name: ENV
      value: q2
  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-fagmodul-q2.intern.dev.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 40
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 40
    failureThreshold: 10
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 4000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi