kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-fagmodul-q2
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  kafka:
    pool: nav-dev
  envFrom:
    - secret: fagmodul-dev #secret name in Google Secret Manager
  azure:
    application:
      enabled: true
      claims:
        extra:
          - NAVident
  accessPolicy:
    outbound:
      rules:
        - application: eessi-pensjon-frontend-ui-fss
          namespace: eessipensjon
          cluster: dev-fss
        - application: eessi-pensjon-frontend-api-fss
          namespace: eessipensjon
          cluster: dev-fss
        - application: eessi-pensjon-prefill-q2
          namespace: eessipensjon
          cluster: dev-gcp
    inbound:
      rules:
        - application: eessi-pensjon-journalforing-q2
          namespace: eessipensjon
          cluster: dev-gcp
  webproxy: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: PENSJONSINFORMASJON_URL
      value: https://eessi-pensjon-onprem-proxy-q2.dev-fss-pub.nais.io/pen/api/pensjonsinformasjon/v1
    - name: EESSIPEN_EUX_RINA_URL
      value: https://eux-rina-api-q2.nais.preprod.local/cpi
    - name: EESSIPENSJON_PREFILL_GCP_URL
      value: https://eessi-pensjon-prefill-q2.dev.intern.nav.no
    - name: RINA_HOST_URL
      value: rina-ss1-q.adeo.no
    - name: SAF_GRAPHQL_URL
      value: https://saf-q2.dev-fss-pub.nais.io/graphql
    - name: SAF_HENTDOKUMENT_URL
      value: https://saf-q2.dev-fss-pub.nais.io/rest/hentdokument
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: ONPREM_KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: KAFKA_STATISTIKK_TOPICNAME
      value: eessipensjon.privat-statistikk-q2
    - name: KAFKA_AUTOMATISERING_TOPIC
      value: eessipensjon.public-automatisering-q2
    - name: KODEVERK_REST_API_URL
      value: https://eessi-pensjon-onprem-proxy-q2.dev-fss-pub.nais.io
    - name: EESSI_PEN_ONPREM_PROXY_URL
      value: https://eessi-pensjon-onprem-proxy-q2.dev-fss-pub.nais.io
    - name: EESSI_PENSJON_INSTITUSJON
      value: NO:NAVAT07
    - name: EESSI_PENSJON_INSTITUSJON_NAVN
      value: NAV ACCEPTANCE TEST 07
    - name: AZURE_APP_PREFILL_CLIENT_ID
      value: dev-gcp.eessipensjon.eessi-pensjon-prefill-q2
    - name: ENV
      value: q2
  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-fagmodul-q2.nais.preprod.local
    - https://eessi-pensjon-fagmodul-q2.dev-fss-pub.nais.io
    - https://eessi-pensjon-fagmodul-q2.dev.intern.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 40
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 40
    failureThreshold: 10
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 80
  resources:
    limits:
      cpu: "4"
      memory: 8096Mi
    requests:
      cpu: 400m
      memory: 4024Mi
