name: Bygg og deploy Q2

on:
  push:
    branches:
      - master
jobs:
  tag_build_and_deploy:
    name: 'Build, deploy and tag'
    runs-on: ubuntu-latest
    steps:
      # PULLER REPO
      - name: 'Pull repo'
        uses: actions/checkout@v1

      # SETTER DATO OG COMMIT VARIABEL
      - name: 'Setter dato og commit variabel'
        run: |
          export TZ=CET
          echo "::set-env name=DATE::$(date "+%Y-%m-%d--%H-%M-%S")"
          echo "::set-env name=COMMIT_HASH::$(git rev-parse HEAD)"

      # SETTER IMAGE VARIABEL
      - name: 'Setter Image'
        run: echo "::set-env name=IMAGE::docker.pkg.github.com/${{ github.repository }}/eessi-pensjon-fagmodul:${{ env.DATE }}---${{ env.COMMIT_HASH }}"

      # BYGGER DOCKER CONTAINER
      - name: 'Bygg og publiser docker image'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export TZ=CET
          ./gradlew -Pgithub clean build
          docker build --tag ${{ env.IMAGE }} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${{ secrets.GITHUB_TOKEN }}
          docker push ${{ env.IMAGE }}

      # DEPLOYER TIL NAIS -Q2
      - name: 'Deploy to NAIS'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/dev-fss-q2.yml
          VARS: nais/dev-fss-q2.json
          IMAGE: ${{ env.IMAGE }}

      # OPPRETTER GIT TAG
      - name: 'Opprett git tag'
        run: |
          curl -v -s -X POST https://api.github.com/repos/navikt/eessi-pensjon-fagmodul/git/refs -H "Authorization: token  ${{ secrets.GITHUB_TOKEN }}" -d '{ "ref": "refs/tags/${{ env.DATE }}---${{ env.COMMIT_HASH }}",  "sha": "${{ env.COMMIT_HASH }}" }'

      - name: 'Opprette image env for Deploy Q1 job'
        shell: bash
        run: |
          echo "${{ env.IMAGE }}" > imagedeployq1tag.txt
          cat imagedeployq1tag.txt

      - name: 'Upload env for Deploy Q1 job'
        uses: actions/upload-artifact@v1
        with:
          name: tagdeployQ1
          path: imagedeployq1tag.txt

  tag_deploy_q1:
    needs: tag_build_and_deploy
    name: 'Deploy Q1'
    runs-on: ubuntu-latest
    steps:
      - name: 'Download env from Q2 job'
        uses: actions/download-artifact@v1
        with:
          name: tagdeployQ1

      # SETTER IMAGE VARIABEL
      - name: 'Setter Image'
        shell: bash
        run: |
          cat tagdeployQ1/imagedeployq1tag.txt
          echo "::set-env name=IMAGE::$(cat `tagdeployQ1/imagedeployq1tag.txt`)"

      - name: 'Display Image'
        run: echo "{{ env.IMAGE }}"

      # DEPLOYER TIL NAIS -Q1
      - name: 'Deploy to NAIS Q1'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/dev-fss-q1.yml
          VARS: nais/dev-fss-q1.json
          IMAGE: ${{ env.IMAGE }}
